---
- name: Superset
  hosts: superset
  become: yes
  become_method: sudo
  become_user: ubuntu
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt update && sudo apt-get -y install python'


- name: Superset
  hosts: superset
  become: yes
  become_method: sudo
  become_user: root
  
  roles:
  - { role: common , tags: "common"} 
  - { role: mysql , tags: "mysql"}
  - { role: superset  , tags: "superset"} 
  - { role: nginx , tags: "nginx"}
  - { role: end , tags: "end"}



  


    


