---
- name: Pre_Superset
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:


- name: Superset
  hosts: all
  become: yes
  become_method: sudo

  roles:
  - { role: common , tags: "common"} 
  - { role: cloud , tags: "cloud"} 
  - { role: mysql , tags: "mysql"}
  - { role: nginx , tags: "nginx"}
  - { role: superset , tags: "superset"}
  - { role: end  , tags: "end"}  
  



  


    


