#1 Prepare for install
- name: Create Superset User
  user:
    name: superset
    shell: /usr/sbin/nologin
    create_home: no
    
- name: Create Superset-data directory
  file:
    path: /data/wwwroot/superset-data
    state: directory
    owner: superset
    group: superset

- name: Download and unarchive Superset
  unarchive:
    src: "{{superset_download_url}}"
    dest: /data/wwwroot
    remote_src: yes
    
- name: Rename Superset
  shell: if [ $( ls | grep "incubator-superset") ]; then mv incubator-superset* superset; fi
  args:
    chdir: /data/wwwroot

- name: Docker compose Superset
  shell: |
    docker-compose up -d
    docker-compose exec superset bash /app/docker-init.sh
  args:
    chdir: /data/wwwroot/superset

#2 Install by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

#3 configure Superset
