#1 Prepare for install
- name: Create Superset User
  user:
    name: superset
    shell: /usr/sbin/nologin
    create_home: no

- name: delete old installfiles
  shell: rm -rf /data/wwwroot/*
  
- name: Create Superset-data directory
  file:
    path: /data/wwwroot/superset_data
    state: directory
    owner: superset
    group: superset

- name: Download and unarchive Superset
  unarchive:
    src: "{{superset_download_url}}"
    dest: /data/wwwroot
    remote_src: yes
    
- name: Rename Superset
  shell: if [ $( ls | grep "incubator-superset") ]; then mv incubator-superset* superset; fi
  args:
    chdir: /data/wwwroot

#2 Install by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
  
#3 docker-compose add phppgadmin and config
- name: docker-compose add phppgadmin and config
  blockinfile:
    path: /data/wwwroot/superset/docker-compose.yml
    insertafter: "- db_home:/var/lib/postgresql/data"
    block: |
      #add container phppgadmin
        phppgadmin:
          restart: unless-stopped
          image: dockage/phppgadmin
          ports:
            - "9090:80"
          environment:
            - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
            - PHP_PG_ADMIN_SERVER_HOST=db

- name: Docker compose Superset
  shell: |
    docker-compose up -d
  args:
    chdir: /data/wwwroot/superset

- name: Run docker phppgadmin
  shell:
    docker-compose up -d
  args:
    chdir: /data/config/docker/

#4 configure Superset
- name: Create soft link
  shell:
    ln -sf /var/lib/docker/volumes /data/wwwroot/superset_data
    ln -sf /data/wwwroot/superset/docker  /data/wwwroot/superset_data
    ln -sf /data/wwwroot/superset/postgre  /data/wwwroot/superset_data
    ln -sf /data/wwwroot/superset/postgre-frontend  /data/wwwroot/superset_data

#5 version output
- name: Check Graylog Version
  shell: |
    sudo echo -e "superset_version: `docker exec -it superset_superset_1 /bin/bash -c 'cat /usr/local/bin/superset | sed -n 3p |cut -b 34-39'`\n" |sudo tee -a /data/logs/install_version.txt
    sudo echo -e "postgres_version: `docker exec -it superset_db_1 /bin/bash -c 'psql -V |cut -d " " -f 3'`\n" |sudo tee -a /data/logs/install_version.txt
    sudo echo -e "redis_version: `docker exec -it superset_redis_1 /bin/bash -c '/usr/local/bin/redis-server -v |cut -d " " -f 3 |cut -d "=" -f 2'`\n" |sudo tee -a /data/logs/install_version.txt

