#1 Prepare for install
- name: Create Superset User
  user:
    name: superset
    shell: /usr/sbin/nologin
    create_home: no

- name: Create Superset directory
  file:
    path: /data/wwwroot/superset
    state: directory
    owner: superset
    group: superset

- name: Download superset
  get_url:
    dest: /data/wwwroot/superset
    url: "{{superset_download_url}}"
    owner: superset
    group: superset

- name: Docker compose Superset
  shell: docker-compose up
  args:
    chdir: /data/wwwroot/superset

#2 Install by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

#3 configure Superset
