#1 Prepare for install
- name: Create Superset User
  user:
    name: superset
    shell: /usr/sbin/nologin
    create_home: no
    
- name: Create Superset-data directory
  file:
    path: /data/wwwroot/superset_data
    state: directory
    owner: superset
    group: superset

- name: Download and unarchive Superset
  unarchive:
    src: "{{superset_download_url}}"
    dest: /data/wwwroot
    remote_src: yes
    
- name: Rename Superset
  shell: if [ $( ls | grep "incubator-superset") ]; then mv incubator-superset* superset; fi
  args:
    chdir: /data/wwwroot

- name: Docker compose Superset
  shell: |
    docker-compose up -d
  args:
    chdir: /data/wwwroot/superset

#2 Install by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

#3 configure Superset
  
- name: Create soft link
  shell:
    ln -sf /var/lib/docker/volumes /data/wwwroot/superset_data
    ln -sf /data/wwwroot/superset/docker  /data/wwwroot/superset_data
    ln -sf /data/wwwroot/superset/postgre  /data/wwwroot/superset_data
    ln -sf /data/wwwroot/superset/postgre-frontend  /data/wwwroot/superset_data

#3 version output
- name: Check Graylog Version
  shell: |
    sudo echo  `docker exec -it superset_db_1 /bin/bash -c "psql -V"` |sudo tee -a /data/logs/install_version.txt
    sudo echo  `docker exec -it superset_superset_1 /bin/bash -c "superset version |grep Superset"` |sudo tee -a /data/logs/install_version.txt
    sudo echo  `docker-compose exec redis bash -c "/usr/local/bin/redis-server -v "` |sudo tee -a /data/logs/install_version.txt
  args:
    chdir: /data/wwwroot/superset

